apps_login/urls.py
from django.conf.urls import url
from .views import index
from .custom_auth import *

urlpatterns=[
    url(r'^$', index, name='index'),

    # custom auth
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),

]

deadline/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView

import apps_login.urls as apps_login
import apps_profile.urls as apps_profile
import apps_riwayat.urls as apps_riwayat
import apps_search.urls as apps_search
import apps_status.urls as apps_status

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mahasiswa/profile/',include(apps_profile,namespace='profile')),
    url(r'^mahasiswa/riwayat/', include(apps_riwayat,namespace='riwayat')),
	url(r'^mahasiswa/search/', include(apps_search,namespace='search')),
    url(r'^mahasiswa/login/', include(apps_login,namespace='login')),
	url(r'^mahasiswa/status/', include(apps_status,namespace='status')),
    url(r'^$', RedirectView.as_view(url='/mahasiswa/login/',permanent='true'), name='index'),
]

apps_login/models.py
from django.db import models

# Create your models here.

apps_login/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
#catatan: tidak bisa menampilkan messages jika bukan menggunakan method 'render'

response = {}

# NOTE : untuk membantu dalam memahami tujuan dari suatu fungsi (def)
# Silahkan jelaskan menggunakan bahasa kalian masing-masing, di bagian atas
# sebelum fungsi tersebut.

# ======================================================================== #
# User Func
# Apa yang dilakukan fungsi INI? #silahkan ganti ini dengan penjelasan kalian
def index(request):
    print ("#==> masuk index")
    if 'user_login' in request.session:
        return HttpResponseRedirect(reverse('profile:index'))
    else:
        html = 'page_login/session/login.html'
        return render(request, html, response)

apps_login/templates/page_login/session/login.html
{% extends "page_login/layout/base.html" %}
{% block content %}
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="rata-tengah">
            <div class="judul">
                <h1> Halaman Login </h1>
                <p class="text-info"> Gunakan <b> akun SSO </b> untuk login </p>
            </div>
            <form action="{% url 'login:auth_login' %}" method="POST">
                {% csrf_token %}
                <p>
                    <label for="username"> Your username </label>
                    <input type="text" id="username" name="username" required>
                </p>
                <p>
                    <label for="password"> Your password </label>
                    <input type="password" id="password" name="password" required>
                </p>
                <input type="submit" class="btn btn-default">
            </form>
        </div>
    </div>
</div>
{% endblock %}