apps_status/urls.py
from django.conf.urls import url
from .views import index, update_status, delete_status

urlpatterns=[
    url(r'^$', index, name='index'),
    url(r'^update_status/', update_status,name='update_status'),
    url(r'^delete_status/',delete_status,name='delete_status'),
]

deadline/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView

import apps_login.urls as apps_login
import apps_profile.urls as apps_profile
import apps_riwayat.urls as apps_riwayat
import apps_search.urls as apps_search
import apps_status.urls as apps_status

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mahasiswa/profile/',include(apps_profile,namespace='profile')),
    url(r'^mahasiswa/riwayat/', include(apps_riwayat,namespace='riwayat')),
	url(r'^mahasiswa/search/', include(apps_search,namespace='search')),
    url(r'^mahasiswa/login/', include(apps_login,namespace='login')),
	url(r'^mahasiswa/status/', include(apps_status,namespace='status')),
    url(r'^$', RedirectView.as_view(url='/mahasiswa/login/',permanent='true'), name='index'),
]

apps_status/models.py
from django.db import models
from apps_profile.models import User

# Create your models here.

class Status(models.Model):
    user = models.ForeignKey(User, default="kosong")
    status = models.CharField(max_length=140)
    created_date = models.DateTimeField(auto_now_add=True)

apps_status/forms.py
from django import forms

class Status_Form(forms.Form):
    attrs = {
        'type': 'text',
        'class': 'status_form',
        'placeholder':'What are you thinking today?',
    }
    status = forms.CharField(label='', required=True, max_length=140, widget=forms.Textarea(attrs=attrs))

apps_status/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from .forms import Status_Form
from django.urls import reverse
from .models import Status
from apps_profile.models import User
from apps_login.csui_helper import get_data_user
# Create your views here.

response = {}
def index(request):
    if 'user_login' in request.session:
        npm = request.session['kode_identitas']
        access_token = request.session['access_token']
        nama = get_data_user(access_token,npm)['nama']
        response['npm']=request.session['kode_identitas']
        user = User.objects.get(npm=npm)
        response['status_form'] = Status_Form
        response['list_status'] = Status.objects.filter(user=user).all()[::-1]
        html = 'apps_status/status.html'
        response['author'] = request.session['user_login']
        status = Status.objects.filter(user=user)
        response['total_post'] = status.count()
        response['name'] = nama
        if(status.count()>0):
            response['status'] = status.order_by('-id')[0].status
        if 'user_login' in request.session:
            npm = request.session['kode_identitas']          
        return render(request,html,response)
    else :
        return HttpResponseRedirect(reverse('login:index'))

def update_status(request):
    form = Status_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        status = request.POST['status']
        if 'user_login' in request.session:
            npm = request.session['kode_identitas']
            user = User.objects.get(npm=npm)
            status = Status(status = status, user=user)
            status.save()
    return HttpResponseRedirect('/mahasiswa/status/')

def delete_status(request):
    if(request.method == 'POST'):
        id = int(request.POST['id'])
        Status.objects.filter(id=id).delete()
    return HttpResponse(' ')

apps_status/templates/apps_status/status.html
{% extends "base.html" %} {% load staticfiles %} {% block static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/update_status.css' %}" />
{% endblock %}

{% block script %}
<script>
$(".delete-button").on("click",function(){
	var id = $(this).data('id');
	$.ajax({
		url:"delete_status",
		type:"POST",
		data:{csrfmiddlewaretoken:document.getElementsByName('csrfmiddlewaretoken')[0].value, "id":id},
		dataType: "json",
	});
	location.href="/status/";
});
</script>
{% endblock %}

{% block content %}
<section>
<form id="form" method="POST" action="{% url 'status:update_status' %}" }>
	{% csrf_token %}
	{{ status_form }}
	<br/>
	<input class="btn btn-lg	 btn-primary btn-info" id="submit" type="submit" value="Post">
</form>
</section>
<section>
<ul class="timeline">
	{% if status %}
  {% for data in list_status %}
	<li>
		<div class="avatar">
				<img src="{% static 'img/profil.jpg' %}">
					<div class="hover">
					<a href="{% url 'profile:index'%}">Click</a>
				</div>
		</div>
		<div class="bubble-container">
			<div class="bubble">
				<h3>{{author}}</h3><br/>
				{{data.status}}
				<div class="date">{{data.created_date}}</div>
				<div class="over-bubble">
					<div class="delete-button">Delete</div>
				</div>
			</div>

		</div>
	</li>
  {% endfor %}
</ul>
  {% else %}
    <div class="alert alert-danger text-center">
        <strong>Sorry!</strong> You haven't updated your status.
    </div>
  {% endif %}
</section>

{% endblock %}