apps_login/urls.py
from django.conf.urls import url
from .views import index
from .custom_auth import *

urlpatterns=[
    url(r'^$', index, name='index'),

    # custom auth
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),

]

apps_profile/urls.py
from django.conf.urls import url
from .views import index,profile,edit_profile,get_json

urlpatterns=[
    url(r'^$', index, name='index'),
    url(r'(?P<npm>\d+)/edit/$',edit_profile,name='edit'),
    url(r'(?P<npm>\d+)/$',profile,name='profile'),
    url(r'(?P<npm>\d+)/json/$',get_json,name='json'),
]

deadline/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView

import apps_login.urls as apps_login
import apps_profile.urls as apps_profile
import apps_riwayat.urls as apps_riwayat
import apps_search.urls as apps_search
import apps_status.urls as apps_status

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mahasiswa/profile/',include(apps_profile,namespace='profile')),
    url(r'^mahasiswa/riwayat/', include(apps_riwayat,namespace='riwayat')),
	url(r'^mahasiswa/search/', include(apps_search,namespace='search')),
    url(r'^mahasiswa/login/', include(apps_login,namespace='login')),
	url(r'^mahasiswa/status/', include(apps_status,namespace='status')),
    url(r'^$', RedirectView.as_view(url='/mahasiswa/login/',permanent='true'), name='index'),
]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %} {% load static %}

<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="SIAK-DEADLINE">
  <meta name="author" content="Benny Ghalsa Miki Tirta">
  <!-- bootstrap css -->
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
  <!-- Font Family -->
  <link href="https://fonts.googleapis.com/css?family=Bungee+Shade" rel="stylesheet"> {% block static %}
  <!-- stylesheet goes here-->
  {% endblock %}
  <title>
    {% block title %} Welcome to SIAK-DEADLINE {% endblock %}
  </title>
</head>

<body>
  <div class="innerwrap">
    <section class="section1 clearfix">
      <div>
        <div class="row grid clearfix">
          <div class="col2 first">
            <img src="http://images.contactmusic.com/newsimages/david_beckham_1133321.jpg" alt="">
            <h1>{{ name }}</h1>
            <p>{{ status }}</p>
            <span id="logout"><a href="{% url 'login:auth_logout' %}">Logout</a></span>
          </div>
          <div class="col2 last">
            <div class="grid clearfix">
              <div class="col3 first">
                <h1>{{ total_post }}</h1>
                <span>Posts </span>
              </div>
              <div class="col3">
                <h1 id="forum">Forum</h1>
              </div>
              <div class="col3 last">
                <h1 id="edit"><a href="{% url 'profile:edit' npm %}">Edit</a></h1>
              </div>
            </div>
          </div>
        </div>
        <div class="row clearfix">
          <ul class="row2tab clearfix">
            <li><i class="fa fa-home"></i><a href="{% url 'status:index' %}"> My Status </a> </li>
            <li><i class="fa fa-user"></i><a href="{% url 'profile:index' %}"> My Profile </a></li>
            <li><i class="fa fa-list-alt"></i><a href="{% url 'riwayat:index' %}"> My History</a></li>
            <li><i class="fa fa-search "></i><a href="{% url 'search:index' %}"> Search </a></li>
          </ul>
        </div>
      </div>
    </section>
  </div>
  <content>
    {% block content %}
    <!-- content goes here -->
    {% endblock %}
  </content>
  <footer>
    <div>
    <p> &copy; Benny Miki Ghalsa Tirta</p>
  </div>
  </footer>

  <!-- Jquery n Bootstrap Script -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script>
    $(document).ready(function() {
      // get current URL path and assign 'active' class
      var pathname = window.location.pathname;
      $('.row2tab > li >  a[href="' + pathname + '"]').parent().addClass('row2tab-active');
    })
  </script>
  {% block script %}
  <!-- script goes here -->
  {% endblock %}
</body>

</html>